---
# Template created with Packer or manually
base_vm_template: BASE_TEMPLATE_alpine

# Project/environment specific template created with Catapult with base_vm_template as source
vm_template: catapult-template-alpine

# Network configuration method.
# Using the default 'interfaces' for Alpine Linux which uses /etc/network/interfaces
customization_method: interfaces
