---
# Template created with Packer or manually
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_fedora_workstation

# vCenter Template name
vm_template: catapult-template-fedora-workstation
