---
# Accounts
admin_account: root
template_username: "{{ admin_account }}"

# Connection
ansible_python_interpreter: /usr/bin/python3
customization_method: macos
default_connection_plugin: ssh
default_ansible_shell_type: sh

# Become
default_ansible_become: true
default_ansible_become_user: "{{ admin_account }}"

# Predefined here because cannot gather facets on MacOS that has no Python installed
ansible_system: Darwin
