---
# Accounts
admin_account: admin
template_username: "{{ admin_account }}"

# Connection
default_connection_plugin: ssh
default_ansible_shell_type: sh

# Become overrides
default_ansible_become_user: root

# Network
ansible_network_os: pfsense # Not natively supported by Ansible but Catapult can use it to determine the correct tasks to run
customization_method: pfsense
