---
# Template created with Packer or manually
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_ubuntu_desktop2404

# vCenter Template name
vm_template: catapult-template-ubuntu-desktop2404

# AWS EC2 Image using owner ID & string lookup because machine IDs are different between regions
ami_owner_id: "099720109477"
ami_name_search_string: ubuntu/images/hvm-ssd-gp3/ubuntu-noble*
aws_template_username: ubuntu
aws_vm_size: m5.large # Recommended by vendor

# Linode Image curl https://api.linode.com/v4/images | jq
linode_image: linode/ubuntu24.04

# Azure
azure_vm_size: Standard_D2s_v3 # Recommended by vendor
azure_vm_image:
  offer: ubuntu-24_04-lts
  publisher: canonical
  sku: server-gen1
  version: latest
